:GUID: %unique_guid%
:OSP_DOMAIN: %dns_zone%
:TOWER_URL: %tower_url%
:TOWER_ADMIN: %tower_admin%
:TOWER_ADMIN_PASSWORD: %tower_admin_password%
:SATELLITE_URL: %satellite_url%
:SATELLITE_ADMIN: %satellite_admin%
:SATELLITE_ADMIN_PASSWORD: %satellite_admin_password%
:SSH_COMMAND: %ssh_command%
:SSH_PASSWORD: %ssh_password%
:organization_name: gpte
:source-linenums-option:        
:markup-in-source: verbatim,attributes,quotes
:show_solution: true
:data-uri:
:linkattrs:
:numbered:

== Overview

The lab environment consists of the systems shown here:

[options=header,cols="2,1"]
|====
|Host Name |Description
|`control.{GUID}.{OSP_DOMAIN}` | Control or Jump host for
 external SSH access
|`satellite.{GUID}.{OSP_DOMAIN}` | Satellite Server
|`node.{GUID}.{OSP_DOMAIN}` | Satellite client
|`tower.{GUID}.{OSP_DOMAIN}` | Ansible Tower Server
|====

== Environment Access
=== Set Up SSH

You must have an SSH connection to your environment.
To access your control system via SSH, use your personal OPENTLC SSO
username and public SSH key.

[NOTE]
Unless noted otherwise, you cannot use SSH to connect directly as `root`.
If you have not already done so, you must provide a public SSH key.
. Go to the link:https://www.opentlc.com/account/[OPENTLC Account Management page^] and click *Update SSH Key*
. Paste your public key in the appropriate field.

[TIP]
For more information on generating an SSH key, see link:https://www.opentlc.com/ssh.html[Setting Up an SSH Key Pair^]

=== SSH into System

Use SSH to remotely connect to the lab control host using your private SSH key,
OPENTLC SSO username, and personal GUID:

+
[source,bash,subs="attributes,verbatim"]
----
$ {SSH_COMMAND} -i path-to-your-ssh-key
----

=== Become Devops User

The Devops User has full ssh capabilities into the other systems in the environment as needed.

After successfully logging in to the control node, become the `devops` user:

+
[source,bash,subs="attributes,verbatim"]
----
$ sudo su - devops
----